def makeList():

    num_features = [

        "ハードツービート",
        "サンシー",
        "Marsayas",
        "Siberian Express",
        "Mat de Cocagne",
        "Tudor Melody",
        "Chamossaire",
        "Kendor",
        "Fleet Nasrullah",
        "Restivo",
        "Val de l'Orne",
        "シアトルダンサー",
        "Zilzal",
        "エブロス",
        "Lord Avie",
        "Irish Castle",
        "Faraway Son",
        "スマートボーイ",
        "Dubai Destination",
        "Thatching",
        "ナリタトップロード",
        "Rockefella",
        "With Approval",
        "セダン",
        "Septieme Ciel",
        "Sing Sing",
        "Groton",
        "ストロベリーロード",
        "Young Generation",
        "サウスアトランティック",
        "Quadrangle",
        "Polynesian",
        "Aggressor",
        "Key to the Kingdom",
        "サンカルロ",
        "シングンオペラ",
        "グランデラ",
        "スピードシンボリ",
        "Royal Gem",
        "ディクタット",
        "デザートキング",
        "スピードワールド",
        "Tornado",
        "Riva Ridge",
        "Battle Joined",
        "Averof",
        "Noble Jay",
        "Bailjumper",
        "ラシアンルーブル",
        "シルバーチャーム",
        "Raven's Pass",
        "Aristophanes",
        "Into Mischief",
        "Petition",
        "Halling",
        "ウイニングチケット",
        "Belong to Me",
        "Endeavour",
        "Roman",
        "ナリタブライアン",
        "Minnesota Mac",
        "ポツセ",
        "シャーディー",
        "Runaway Groom",
        "Great Nephew",
        "ブレイクランアウト",
        "ゴスホークケン",
        "Honour and Glory",
        "ノーザンディクテイター",
        "Al Nasr",
        "Bold Forbes",
        "ヤマニンスキー",
        "Reflected Glory",
        "Ragusa",
        "Easy Goer",
        "バンブーアトラス",
        "Tudor Minstrel",
        "Distant View",
        "Sir Tristram",
        "Your Host",
        "Relic",
        "Intikhab",
        "High Chaparral",
        "ダイナガリバー",
        "Boundary",
        "バンブーエール",
        "Con Brio",
        "ターゴワイス",
        "Dunce",
        "Gallant Romeo",
        "Northern Baby",
        "Deputed Testamony",
        "Dashing Blade",
        "スノッブ",
        "Alcide",
        "Maria's Mon",
        "Seattle Song",
        "Bluebird",
        "Well Decorated",
        "Oasis Dream",
        "クリストワイニング",
        "Siyouni",
        "メジロサンマン",
        "エルハーブ",
        "ホリスキー",
        "Assert",
        "Antheus",
        "アスワン",
        "Wavering Monarch",
        "Gallant Man",
        "Procida",
        "Teofilo",
        "Native Charger",
        "Green God",
        "ゼンノエルシド",
        "Menetrier",
        "Sea The Stars",
        "Silent Screen",
        "Green Forest",
        "Cherokee Run",
        "Nantallah",
        "Candy Ride",
        "Road At Sea",
        "Dan Cupid",
        "Exchange Rate",
        "Marju",
        "スパイキュール",
        "Candy Stripes",
        "Rambunctious",
        "Tentam",
        "Roan Rocket",
        "Cee's Tizzy",
        "Sinndar",
        "Salt Lake",
        "Carson City",
        "パークリージェント",
        "Bernstein",
        "アローエクスプレス",
        "Lithiot",
        "Selkirk",
        "コマンズ",
        "タケシバオー",
        "アレミロード",
        "フサイチセブン",
        "Ghostzapper",
        "Illustrious",
        "デクラレーションオブウォー",
        "Scat Daddy",
        "Indian Ridge",
        "Congrats",
        "ゲイメセン",
        "Olympia",
        "New Approach",
        "メイショウオウドウ",
        "Crafty Admiral",
        "ノーザリー",
        "Carr de Naskra",
        "Bold Hour",
        "Lost Code",
        "Salieri",
        "On-And-On",
        "ウォーターリーグ",
        "Great Above",
        "My Babu",
        "マルカシェンク",
        "ホッコータルマエ",
        "Sauce Boat",
        "リヴリア",
        "Forest Wildcat",
        "Dark Star",
        "Hard Work",
        "Master Derby",
        "In Excess",
        "スターオブコジーン",
        "Alysheba",
        "Hero's Honor",
        "Cyane",
        "サンライズペガサス",
        "ヤマニンセラフィム",
        "ニューイングランド",
        "Phone Trick",
        "Cryptoclearance",
        "シルポート",
        "Stage Door Johnny",
        "Fastnet Rock",
        "プルラリズム",
        "Baldski",
        "Sir Wiggle",
        "ブラックタキシード",
        "マリーノ",
        "Holy Bull",
        "General",
        "Ajdal",
        "What Luck",
        "エルセンタウロ",
        "Chieftain",
        "Kazan",
        "Traffic Judge",
        "Cohoes",
        "スマートロビン",
        "Creme dela Creme",
        "Uncle Mo",
        "レッドスパーダ",
        "ダノンバラード",
        "Cadeaux Genereux",
        "Henry the Seventh",
        "Best Turn",
        "Nebos",
        "Full Out",
        "シャトーゲイ",
        "Abdos",
        "Ticino",
        "Vindication",
        "ハイアーゲーム",
        "シーホーク",
        "ソヴィエトスター",
        "Daryl's Joy",
        "トライバルチーフ",
        "シービークロス",
        "Polar Falcon",
        "ミスターシービー",
        "Prince Chevalier",
        "Balidar",
        "スニッツェル",
        "オンファイア",
        "クリエイター",
        "Highest Honor",
        "Caucasus",
        "Valid Appeal",
        "Dayjur",
        "Harlan's Holiday",
        "Rubiano",
        "ダンディルート",
        "Marquetry",
        "Naevus",
        "Pall Mall",
        "Lucky Mel",
        "Lord Gayle",
        "Harvest Singing",
        "Bald Eagle",
        "ディアブロ",
        "Never Say Die",
        "Chop Chop",
        "フサイチリシャール",
        "Slew o' Gold",
        "ヒンドスタン",
        "Delta Judge",
        "Mister Frisky",
        "スリルショー",
        "ブラックホーク",
        "Pioneerof the Nile",
        "Lomond",
        "Green Ticket",
        "エイシンサンディ",
        "パントレセレブル",
        "Whitesburg",
        "Vandale",
        "Star Appeal",
        "Kitten's Joy",
        "ロドリゴデトリアーノ",
        "ラブリーデイ",
        "ヒルノダムール",
        "Charlottesville",
        "Smadoun",
        "Tantieme",
        "Cox's Ridge",
        "Val de Loir",
        "リンカーン",
        "Prince Rose",
        "Jimmy Reppin",
        "Birkhahn",
        "Time for a Change",
        "Tiepoletto",
        "モデルフール",
        "General Assembly",
        "Authi",
        "Malibu Moon",
        "マリエンバード",
        "Bold Lad",
        "New Providence",
        "クリスタルグリッターズ",
        "ダンサーズイメージ",
        "Occupy",
        "Niniski",
        "Grey Sovereign",
        "Labus",
        "Polish Precedent",
        "Cold Reception",
        "シャンハイ",
        "ヴァンセンヌ",
        "アルカセット",
        "テンビー",
        "オウケンブルースリ",
        "ソングオブウインド",
        "ヴァイスリーガル",
        "Turkoman",
        "エアジハード",
        "Pia Star",
        "Lear Fan",
        "Spectacular Bid",
        "Sassafras",
        "Redoute's Choice",
        "Stanford",
        "Fly So Free",
        "ブラックタイアフェアー",
        "The Axe",
        "アジアエクスプレス",
        "War Front",
        "ジェニュイン",
        "Awesome Again",
        "Crozier",
        "Concerto",
        "Carvin",
        "サクラローレル",
        "Tiznow",
        "Tamerlane",
        "ミッキーアイル",
        "イングリッシュプリンス",
        "ヒッティングアウェー",
        "アーテイアス",
        "セクレト",
        "Hurry Up Blue",
        "Presidium",
        "Dynaformer",
        "Fabulous Dancer",
        "Grand Lodge",
        "エイシンアポロン",
        "Bull Page",
        "トーセンブライト",
        "スクワートルスクワート",
        "フォーティナイナーズサン",
        "Homing",
        "Quiet American",
        "Danehill Dancer",
        "Deploy",
        "Kenmare",
        "Stop the Music",
        "ヴィエナ",
        "Majestic Prince",
        "ジャッジアンジェルーチ",
        "Nasram",
        "Indian Charlie",
        "Klairon",
        "Zafonic",
        "シビルウォー",
        "Milesian",
        "ジョリーズヘイロー",
        "Saint Ballado",
        "More Than Ready",
        "Violon d'Ingres",
        "Verbatim",
        "What a Pleasure",
        "Tale of the Cat",
        "タヤスツヨシ",
        "リィフォー",
        "Matrice",
        "Noholme",
        "Tim Tam",
        "Mt. Livermore",
        "Grand Slam",
        "Diesis",
        "Preciptic",
        "Smarten",
        "Connaught",
        "Sunrise Flight",
        "Birdstone",
        "Red Ransom",
        "ファンタスティックライト",
        "Forestry",
        "Mr. Leader",
        "トーセンファントム",
        "Invincible Spirit",
        "アーネストリー",
        "アドマイヤジャパン",
        "Kaldoun",
        "Broad Brush",
        "Mo Exception",
        "シルバーシャーク",
        "オレハマッテルゼ",
        "Bernardini",
        "マクフィ",
        "スズカコーズウェイ",
        "スピニングワールド",
        "Fine Top",
        "Luthier",
        "Speightstown",
        "ロイヤルアカデミー",
        "スティールハート",
        "リンドシェーバー",
        "Ambehaving",
        "Ambiorix",
        "ピットカーン",
        "Raise a Cup",
        "ディスクリートキャット",
        "タマモクロス",
        "Cure the Blues",
        "War Admiral",
        "Olden Times",
        "ファバージ",
        "Troy",
        "ミラクルアドマイヤ",
        "Shamardal",
        "Double Jay",
        "Ack Ack",
        "ドクターデヴィアス",
        "Court Martial",
        "アドマイヤオーラ",
        "Worden",
        "オンリーフォアライフ",
        "Known Fact",
        "Vigors",
        "Al Hattab",
        "グルームダンサー",
        "ボールドラツド",
        "カーネギー",
        "ジェネラス",
        "スウィフトカレント",
        "Tyrant",
        "スタチューオブリバティ",
        "Acropolis",
        "Hethersett",
        "キャプテンスティーヴCaptain Steve",
        "Utrillo",
        "Pivotal",
        "Swaps",
        "Lord at War",
        "チャイナロック",
        "Tom Cat",
        "Pretense",
        "Grindstone",
        "サンプリンス",
        "リオンディーズ",
        "ノボジャック",
        "サザンヘイロー",
        "Majestic Light",
        "サクラプレジデント",
        "Jester",
        "Search Tradition",
        "Pass the Tab",
        "ノノアルコ",
        "Petingo",
        "モンジュー",
        "Our Emblem",
        "キンググローリアス",
        "Beau Max",
        "ナイスダンサー",
        "Medaglia d'Oro",
        "Reviewer",
        "Northfields",
        "Grey Dawn",
        "パドトロワ",
        "Frankel",
        "Dalakhani",
        "カリズマティック",
        "クラウンドプリンス",
        "Lemon Drop Kid",
        "モガミ",
        "タバスコキャット",
        "Conquistador Cielo",
        "ロジユニヴァース",
        "チーフベアハート",
        "スキャン",
        "Mr. Greeley",
        "パラダイスクリーク",
        "ウォーニング",
        "ドゥラメンテ",
        "Hagley",
        "Acatenango",
        "チチカステナンゴ",
        "The Minstrel",
        "トーセンラー",
        "Relaunch",
        "Hyperion",
        "アサティス",
        "High Line",
        "タイトスポット",
        "Spy Song",
        "テイエムオペラオー",
        "Barathea",
        "Topsider",
        "アサクサキングス",
        "Derring-Do",
        "Bupers",
        "サッカーボーイ",
        "サンダーガルチ",
        "Elusive Quality",
        "Akarad",
        "Sure Blade",
        "Plugged Nickle",
        "ストラヴィンスキー",
        "Silver Deputy",
        "トウカイテイオー",
        "Summer Squall",
        "カコイーシーズ",
        "アドマイヤコジーン",
        "ヴェンチア",
        "ダンシングブレーヴ",
        "Summing",
        "Bellamy Road",
        "Reliance",
        "アポロキングダム",
        "シンボリルドルフ",
        "Clandestine",
        "アッミラーレ",
        "ラッキーソブリン",
        "Sicambre",
        "コロナドズクエスト",
        "Lt. Stevens",
        "Pleasant Tap",
        "Garde Royale",
        "Dschingis Khan",
        "メジロライアン",
        "ニホンピロウイナー",
        "Slewpy",
        "トゥザワールド",
        "セントクレスピン",
        "Dr. Fager",
        "キャプテントゥーレ",
        "ゼダーン",
        "ロードアルティマ",
        "The Prime Minister",
        "ミシシッピアン",
        "Bold Bidder",
        "Tapit",
        "Francis S.",
        "エタン",
        "ボストンハーバー",
        "El Prado",
        "サマーバード",
        "ブレイヴェストローマン",
        "スズカフェニックス",
        "カンパニー",
        "Honest Pleasure",
        "ローレルゲレイロ",
        "Mark of Esteem",
        "Venetian Jester",
        "Nearco",
        "Theatrical",
        "アジュディケーティング",
        "メジロアサマ",
        "モーリス",
        "Amerigo",
        "アルデバランＩＩAldebaran",
        "Poker",
        "ガーサント",
        "Dubai Millennium",
        "ラムタラ",
        "Intentionally",
        "ミルジョージ",
        "Ela-Mana-Mou",
        "カレンブラックヒル",
        "スピルバーグ",
        "Bel Bolide",
        "エリシオ",
        "マヤノトップガン",
        "ジョーカプチーノ",
        "Lorenzaccio",
        "Khaled",
        "コンデュイット",
        "トワイニング",
        "Capote",
        "Prove Out",
        "マーベラスサンデー",
        "Kahyasi",
        "Thinking Cap",
        "Ambiopoise",
        "アンライバルド",
        "Naskra",
        "Cutlass",
        "バブルガムフェロー",
        "Private Account",
        "Gulch",
        "エスケンデレヤ",
        "フサイチコンコルド",
        "Lycius",
        "Fusaichi Pegasus",
        "Exclusive Native",
        "アドマイヤベガ",
        "Arctic Tern",
        "Green Dancer",
        "Cormorant",
        "ウォーエンブレム",
        "ゴールドヘイロー",
        "Luciano",
        "デュランダル",
        "パーソロン",
        "アンバーシャダイ",
        "ワールドエース",
        "Ahonoora",
        "Rainbow Quest",
        "スターリングローズ",
        "Nodouble",
        "マイネルラヴ",
        "Lagunas",
        "デヒア",
        "Street Cry",
        "イルドブルボン",
        "ロックオブジブラルタル",
        "Boldnesian",
        "Dixieland Band",
        "Top Ville",
        "Be My Guest",
        "Literat",
        "ハードスパン",
        "Admiral's Voyage",
        "Loup Sauvage",
        "フェノーメノ",
        "Hasty Road",
        "Thatch",
        "Agio",
        "Sea-Bird",
        "Espresso",
        "トビーズコーナー",
        "ローズキングダム",
        "ファスリエフ",
        "オジジアン",
        "Tom Fool",
        "クリスタルパレス",
        "ストリートセンス",
        "Smart Strike",
        "Sword Dancer",
        "Irish River",
        "Affirmed",
        "リアルインパクト",
        "コマンダーインチーフ",
        "Hawaii",
        "Crepello",
        "ストーミングホーム",
        "トランセンド",
        "エスポワールシチー",
        "Hostage",
        "Arch",
        "Mineshaft",
        "Queen's Hussar",
        "Prince John",
        "Cornish Prince",
        "マジェスティックウォリアー",
        "プラティニ",
        "トゥザグローリー",
        "アドマイヤマックス",
        "タイムパラドックス",
        "Night Shift",
        "ヘクタープロテクター",
        "ネヴァービート",
        "スズカマンボ",
        "Shantung",
        "ゴールドシップ",
        "サムライハート",
        "Shareef Dancer",
        "In the Wings",
        "High Top",
        "トウショウボーイ",
        "Habitat",
        "Tri Jet",
        "Dyhim Diamond",
        "Darshaan",
        "Bustino",
        "リーチザクラウン",
        "ドリームジャーニー",
        "ケープブランコ",
        "Nasrullah",
        "ティンバーカントリー",
        "バトルプラン",
        "Raja Baba",
        "Nashwan",
        "Dubawi",
        "ショウナンカンプ",
        "ディープスカイ",
        "Cozzene",
        "フリオーソ",
        "グランプリボス",
        "Old Trieste",
        "Clever Trick",
        "トーセンジョーダン",
        "Star de Naskra",
        "Devil His Due",
        "フォルティノ",
        "マイニング",
        "メジロティターン",
        "リアルシャダイ",
        "ジェイドロバリー",
        "Pago Pago",
        "Meadowlake",
        "ファルブラヴFalbrav",
        "Konigsstuhl",
        "Sir Gaylord",
        "Surumu",
        "Rahy",
        "Cape Cross",
        "モンテロッソ",
        "Round Table",
        "Vaguely Noble",
        "Bunty's Flight",
        "El Gran Senor",
        "ベルシャザール",
        "Hoist the Flag",
        "Key to the Mint",
        "Fairy King",
        "Green Desert",
        "Victoria Park",
        "ベーカバド",
        "ストロングリターン",
        "Bering",
        "Galileo",
        "Shirley Heights",
        "リマンド",
        "Distorted Humor",
        "バゴ",
        "ケイムホーム",
        "Sanctus",
        "ナカヤマフェスタ",
        "ダンカーク",
        "Law Society",
        "Princely Gift",
        "Red God",
        "Drone",
        "Flower Alley",
        "Princequillo",
        "Bold Reason",
        "カジノドライヴ",
        "Wild Risk",
        "Unbridled's Song",
        "Miswaki",
        "ワイルドラッシュ",
        "Dance Spell",
        "Pleasant Colony",
        "Crimson Satan",
        "シングスピール",
        "Forli",
        "Chief's Crown",
        "ローエングリン",
        "Herbager",
        "Tom Rolfe",
        "ヴァーミリアン",
        "Giant's Causeway",
        "Speak John",
        "Lombard",
        "カネヒキリ",
        "プリサイスエンド",
        "ロイヤルスキー",
        "エピファネイア",
        "ホワイトマズル",
        "Crafty Prospector",
        "Gold Meridian",
        "オペラハウス",
        "Monsun",
        "ダノンシャンティ",
        "メイショウサムソン",
        "Ribot",
        "Classic Go Go",
        "エルコンドルパサー",
        "Alleged",
        "タートルボウル",
        "スマートファルコン",
        "シニスターミニスター",
        "アグネスデジタル",
        "Alydar",
        "トーセンホマレボシ",
        "Blakeney",
        "Woodman",
        "ヨハネスブルグ",
        "Pulpit",
        "Mill Reef",
        "キズナ",
        "Sharpen Up",
        "ロージズインメイ",
        "Caro",
        "Riverman",
        "メジロマックイーン",
        "テスコボーイ",
        "Hornbeam",
        "ジャスタウェイ",
        "トライマイベスト",
        "アフリート",
        "Sir Ivor",
        "Bold Reasoning",
        "Fappiano",
        "Wild Again",
        "マツリダゴッホ",
        "Silver Hawk",
        "Dansili",
        "スウェプトオーヴァーボード",
        "Damascus",
        "Gone West",
        "タニノギムレット",
        "マルゼンスキー",
        "Kalamoun",
        "Graustark",
        "キングヘイロー",
        "Hold Your Peace",
        "ノヴェリスト",
        "サクラユタカオー",
        "Never Bend",
        "ディクタス",
        "Machiavellian",
        "メイショウボーラー",
        "Icecapade",
        "Seeking the Gold",
        "His Majesty",
        "パイロ",
        "ワークフォース",
        "アイルハヴアナザー",
        "ヘネシー",
        "スクリーンヒーロー",
        "ディープブリランテ",
        "Bold Ruler",
        "Le Fabuleux",
        "Busted",
        "Native Dancer",
        "アドマイヤムーン",
        "Kris",
        "ヘニーヒューズ",
        "Buckpasser",
        "エイシンフラッシュ",
        "In Reality",
        "Unbridled",
        "サウスヴィグラス",
        "Blushing Groom",
        "Nashua",
        "Devil's Bag",
        "ブラックタイド",
        "ダンスインザダーク",
        "グラスワンダー",
        "ダンシングブレーヴDancing Brave",
        "エンパイアメーカー",
        "ゼンノロブロイ",
        "サクラバクシンオー",
        "ヴィクトワールピサ",
        "Montparnasse",
        "Promised Land",
        "デインヒル",
        "Vice Regent",
        "Caerleon",
        "キンシャサノキセキ",
        "A.P. Indy",
        "スペシャルウィーク",
        "Cosmic Bomb",
        "ジャングルポケット",
        "オルフェーヴル",
        "ハービンジャー",
        "ラストタイクーン",
        "Kris S.",
        "カンパラ",
        "マンハッタンカフェ",
        "ロードカナロア",
        "Storm Bird",
        "ルーラーシップ",
        "タイキシャトル",
        "Turn-to",
        "アグネスタキオン",
        "Alzao",
        "Secretariat",
        "Seattle Slew",
        "フォーティナイナー",
        "エンドスウィープ",
        "キングズベスト",
        "ダイワメジャー",
        "ゴールドアリュール",
        "Deputy Minister",
        "ブライアンズタイム",
        "ネオユニヴァース",
        "シンボリクリスエス",
        "クロフネ",
        "Sadler's Wells",
        "Nearctic",
        "フジキセキ",
        "ハーツクライ",
        "フレンチデピュティ",
        "Nijinsky",
        "ステイゴールド",
        "Danzig",
        "Storm Cat",
        "Lyphard",
        "Roberto",
        "トニービン",
        "Nureyev",
        "ノーザンテースト",
        "Kingmambo",
        "Raise a Native",
        "Understanding",
        "キングカメハメハ",
        "ディープインパクト",
        "Hail to Reason",
        "Mr. Prospector",
        "Northern Dancer",
        "Halo",
        "サンデーサイレンス"
    ]

    return num_features
